plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}


android {
    namespace 'vn.leeon.eidsdk'
    compileSdk 35

    defaultConfig {
        minSdk 26
        targetSdk 35
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
        ndk {
            abiFilters "armeabi-v7a"
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs', 'src/main/jniLibs']
        }
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }
}

dependencies {
    // Local AARs / JARs
    implementation(name: 'fotoapparat-2.7.0', ext: 'aar')
    implementation files('libs/crteid.aar')
    implementation files('libs/jj2000_imageutil.jar')

    implementation fileTree(include: ['*.jar'], dir: 'libs')

    // Core Android + Firebase + ML
    implementation libs.androidx.core.ktx.v1150
    implementation libs.firebase.core
    implementation libs.firebase.ml.common
    implementation 'com.google.android.gms:play-services-mlkit-text-recognition:19.0.1'

    // OCR + MRZ tools
    implementation libs.jmrtd
    implementation libs.prov
    implementation(libs.bcpkix.jdk18on)
    implementation libs.bcprov.jdk18on

    implementation libs.cert.cvc

    // Networking
    implementation libs.retrofit
    implementation libs.converter.gson
    implementation libs.converter.moshi
    implementation 'com.squareup.okhttp3:logging-interceptor:4.11.0'

    // Biometric fingerprint
    implementation libs.jnbis

    // Reactive
    implementation libs.rxandroid
    implementation libs.rxjava

}

